# Generated by Django 5.0.2 on 2024-03-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpstaticapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='team')),
                ('desc', models.TextField()),
            ],
        ),
    ]
